name: .NET Core

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal


    - name: Publish
      run: dotnet publsh -c Release -o '${{ github.workspace }}/out

    - name: microsoft/variable-substitution@v1
      with:
        files: '${{ github.workspace  }}/out/appsettings.json'
      env:
        ConnectionString.myDb1: "ValorExemplo"

    - name: 'Deploy to Azure Web app'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'octobersample2'
        publish-profile: ${{ secrtets.azureWebAppPublishProfile }}
        package: ${{ github.workspace }}/out
