name: Deploy_main
on:
  workflow_dispatch:
  
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v2

     - name: Setup .NET Core
       uses: actions/setup-dotnet@v1
       with:
          dotnet-version: 3.1.101
     - name: Install dependencies
       run: dotnet restore
    
     - name: Build
       run: dotnet build --configuration Release --no-restore
    
     - name: Test
       run: dotnet test --no-restore --verbosity normal

     - name: Publish
       run: dotnet publish -c Release -o '${{ github.workspace }}/out'
            ls -l
            echo 'entrou aqui'
            cd ${{ github.workspace }}/out
            echo 'saiu'
            ls -l
        
     
